@BASE_URL = http://localhost:3000

### GET Users
GET {{BASE_URL}}/users

### GET Products
GET {{BASE_URL}}/products

### GET Search Products
GET {{BASE_URL}}/products/search?name=key

### GET Product by id
GET {{BASE_URL}}/products/2

### POST Add Product
POST {{BASE_URL}}/products
Content-Type: application/json

{
    "name": "Macbook",
    "price": 69000
}

### GET Blogs
GET {{BASE_URL}}/blogs

### GET Blog by blogId
GET  {{BASE_URL}}/blogs/2

### GET Comments
GET {{BASE_URL}}/blogs/comments

### GET Comment by commentId
GET {{BASE_URL}}/blogs/1/comments/2